#ddev-generated
name: seq
services:
    seq:
        image: datalust/seq
        container_name: ddev-${DDEV_SITENAME}-seq
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SEQ_API_CANONICALURI=http://seq.${DDEV_SITENAME}.ddev.site
        volumes:
            - ./seq/data:/data
        ports:
            - 8501:80
            - 5341:5341
        
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        networks:
          - seq-net
networks:
  seq-net:
    name: ddev_default
    external: true
